men_to_load = [
    # 'Christian Bale',
    # 'Vin Diesel',
    # 'Chris Hemsworth',
    'Ryan Reynolds',
    'Tom Hiddleston',
    'Chris Evans',
    'Kumail Nanjiani',
    'Paul Rudd',
    'Keanu Reeves',
    'Simon Baker',
    'Jonathan Majors',
    'Jason Momoa',
    'Mahershala Ali',
    'Arnold Schwarzenegger',
    'Wesley Snipes',
    'Sylvester Stallone',
    'Samuel Jackson',
    'Denzel Washington',
    'Will Smith',
    'Martin Lawrence',
    'Robert Downey Jr.',
    'Jude Law',
    'Matthew McConaughey',
    'Leonardo DiCaprio',
    'Brad Pitt',
    'Johnny Depp',
    'Jackie Chan',
    'Donnie Yen',
    'Jet Li',
    'Mikhail Boyarskiy',
    'Mikhail Porechenkov',
    'Sergei Bodrov Jr.',
    'Danila Kozlovsky',
    'Alexander PETROV',
    'Ivan Okhlobystin',
    'Yuri Nikulin',
    'Georgiy Vitsin',
    'Yevgeny Morgunov'
]
# print(len(men_to_load))