women_to_load = [
    # 'Emma Watson',
    # 'Jennifer Lawrence',
    # 'Selena Gomez',
    'Angelina Jolie',
    'Anne Hathaway',
    'Scarlett Johansson',
    'Jessica Chastain',
    'Natalie Portman',
    'Megan Fox',
    'Charlize Theron',
    'Cameron Diaz',
    'Gal Gadot',
    'Jennifer Aniston',
    'Jessica Alba',
    'Sandra Bullock',
    'Keira Knightley',
    'Paris Hilton',
    'Margot Robbie',
    'Penélope Cruz',
    'Oprah Winfrey',
    'Rihanna',
    'Madonna',
    'Beyonce',
    'Kim Kardashian',
    'Avril Lavigne',
    'Salma Hayek',
    'Michelle Rodriguez',
    'Sigourney Weaver',
    'Zoe Saldana',
    'Kristina Asmus',
    'Svetlana Kamynina',
    'Svetlana Permyakova',
    'Tatyana Lyannik',
    'Rina Grishina',
    'Alexandra Bortich',
    'Irina Vilkova'
]
# print(len(women_to_load))